CREATE TABLE IF NOT EXISTS `reminder` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `TITLE` tinytext NOT NULL,
  `MESSAGE` mediumtext NOT NULL,
  `CREATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USER_ID` tinytext NOT NULL,
  `NOTIFY_TIME` tinytext NOT NULL,
  `MODIFIED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `STATUS` tinytext NOT NULL,
  PRIMARY KEY (`ID`)
);
DELETE FROM `reminder`;
/*!40000 ALTER TABLE `reminder` DISABLE KEYS */;
INSERT INTO `reminder` (`id`, `TITLE`, `MESSAGE`, `CREATED_TIME`, `USER_ID`, `NOTIFY_TIME`, `MODIFIED_TIME`, `STATUS`) VALUES
	(0, '1', '1', '2022-07-10 22:25:27', 'goutham', 'dg', '0000-00-00 00:00:00', 'dg');
